name: flutter_web_cos_upload_plugin
description: A sub plug-in of flutter_web_optimizer，used to upload resources to cos
version: 1.0.2
homepage: https://github.com/TryImpossible/flutter_web_cos_upload_plugin
repository: https://github.com/TryImpossible/flutter_web_cos_upload_plugin
issue_tracker: https://github.com/TryImpossible/flutter_web_cos_upload_plugin/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  # https://pub.flutter-io.cn/packages/path
  path: ^1.8.3
  # https://pub.flutter-io.cn/packages/yaml
  yaml: ^3.1.1
  # https://pub.flutter-io.cn/packages/package_config
  package_config: ^2.1.0
  # https://pub.dev/packages/tencent_cos_plus
  tencent_cos_plus: ^1.2.0
  # https://pub.dev/packages/flutter_web_optimizer
  flutter_web_optimizer: ^1.1.9

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
